server:
  port: 17001
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server2:17002/eureka
  instance:
    hostname: eureka-server1
  server:
    eviction-interval-timer-in-ms: 10000
    registry-sync-retry-wait-ms: 30000
    registry-sync-retries: 5